### ISSUE TITLE
Migration to homebridge !?

### ISSUE THREAD

**Issue by fastenspy** [Aohzan/hass-mcz-maestro#2]
Hello Aohazan,

do you think it is possible to migrate this plugin to homebridge? 

Yours

**Comment by Aohzan** [comment]
hello
you you can do it through home assistant with [the homekit integration](https://www.home-assistant.io/integrations/homekit/), otherwise no I don't think so

**Comment by fastenspy** [comment]
Hello,

Thanks for your quick response. I have only home bridge but No problem i’m tested HA on a new Rpi, i’m copying the files from your git on folder config (with samba). But after restart nothing in the list of device integration ? Need other package or add-ons ?

Best regards

Le 30 oct. 2022 à 16:56, Matthieu ***@***.***> a écrit :

﻿

Closed #2<https://github.com/Aohzan/hass-mcz-maestro/issues/2> as completed.

**Comment by fastenspy** [comment]
Hello Matthieu,

just run your integration (Copied with "File Editor" not samba) Now find in integration list ! I'm connected on MCZ with direct wifi (pic1)
<img width="598" alt="pic1" src="https://user-images.githubusercontent.com/14542142/199219196-abcf0163-015e-4cd8-844b-9347f9a6b7f5.png">

But impossible to connect (see log)

`ogger: aiohttp.server
Source: custom_components/mczmaestro/maestro/__init__.py:12 
Integration: MCZ Maestro ([documentation](https://github.com/Aohzan/hass-mcz-maestro), [issues](https://github.com/Aohzan/hass-mcz-maestro/issues)) 
First occurred: 11:59:01 (1 occurrences) 
Last logged: 11:59:01

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 280, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/mczmaestro/config_flow.py", line 46, in async_step_user
    controller = MaestroController(user_input[CONF_HOST], user_input[CONF_PORT])
  File "/config/custom_components/mczmaestro/maestro/__init__.py", line 12, in __init__
    self._server = websocket.create_connection(
  File "/usr/local/lib/python3.10/site-packages/websocket/_core.py", line 515, in create_connection
    websock.connect(url, **options)
  File "/usr/local/lib/python3.10/site-packages/websocket/_core.py", line 222, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "/usr/local/lib/python3.10/site-packages/websocket/_http.py", line 121, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/usr/local/lib/python3.10/site-packages/websocket/_http.py", line 201, in _open_socket
    raise err
  File "/usr/local/lib/python3.10/site-packages/websocket/_http.py", line 176, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused`
