### ISSUE TITLE
mczmaestro - device info

### ISSUE THREAD

**Issue by jopijuco** [Aohzan/hass-mcz-maestro#7]
Hello @Aohzan 

First, thanks for your work with this integration :+1: 
I've installed your integration, connected to my stove and I'm also able to add a new entry. Although, as soon as I add it fails to set up, shown in the image below.

![Screenshot from 2024-07-16 09-56-53](https://github.com/user-attachments/assets/282d8424-14a4-4a2b-b389-530623718f54)

Looking at the logs, it seems HA couldn't get all the info required to validate the device.

```
Logger: homeassistant.config_entries
Source: config_entries.py:586
First occurred: 9:22:13 AM (5 occurrences)
Last logged: 9:38:34 AM

Error setting up entry MCZ Maestro 192.168.120.1:81 for mczmaestro
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mczmaestro/__init__.py", line 70, in async_setup_entry
    device_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 747, in async_get_or_create
    device_info_type = _validate_device_info(config_entry, device_info)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 244, in _validate_device_info
    raise DeviceInfoError(
homeassistant.helpers.device_registry.DeviceInfoError: Invalid device info {'default_manufacturer': 'MCZ', 'default_model': 'Maestro', 'default_name': 'MCZ Maestro 192.168.120.1:81', 'identifiers': {('mczmaestro', '192.168.120.181')}} for 'mczmaestro' config entry: device info needs to either describe a device, link to existing device or provide extra information.
```

Could you help me with this ?
Thank you.

**Comment by Aohzan** [comment]
Hello,
something incompatible with a HA update I think, I have to check

**Comment by jopijuco** [comment]
Hey @Aohzan, have you had a chance to look at this ?
Thanks.

**Comment by Aohzan** [comment]
Hello, can you test with last update

**Comment by jopijuco** [comment]
Thanks for taking time to look at this :+1: 
I think this new version fixed the previous error, but it seems we're getting a new one:

```
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 10:47:06 PM (5 occurrences)
Last logged: 10:52:30 PM

Error setting up entry MCZ Maestro 192.168.120.1:81 for mczmaestro
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mczmaestro/__init__.py", line 53, in async_setup_entry
    hass.data[DOMAIN][entry.entry_id] = {
    ~~~~~~~~~^^^^^^^^
KeyError: 'mczmaestro'
```

**Comment by Aohzan** [comment]
Indeed, try 0.1.7 version please https://github.com/Aohzan/hass-mcz-maestro/releases/tag/0.1.7

**Comment by jopijuco** [comment]
Awesome ! It's connected !
Thank you very much for your help.
I'll close this issue 👍
